/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import { QRCodeCanvas } from "qrcode.react";
import { ChangeEvent, useRef, useState } from "react";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [value, setValue] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const handleOnChange = (e: ChangeEvent<HTMLInputElement>) => {
    setValue(e.currentTarget.value);
  };

  const download = () => {
    const canvas = document.getElementById("canvas") as HTMLCanvasElement;
    if (!canvas || value == "") {
      inputRef.current?.focus();
      return;
    }
    const link = document.createElement("a");
    link.download = "qrcode.png";
    link.href = canvas.toDataURL();
    link.click();
  };
  return (
    <>
      <Head>
        <title>QR Code Generator by Khoudir Yaya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/qr-code-64.png" />
      </Head>

      <header className={styles.header}>
        <img src="qr-code-64.png" alt="" />
        <h1>QR Code Generator</h1>
      </header>

      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.left}>
            <input
              ref={inputRef}
              type="text"
              onChange={handleOnChange}
              placeholder="Enter your url"
            />
            <div className={styles.info}>
              Your QR code will be generated automatically as you typing
            </div>
            <h2>Examples:</h2>
            <ol>
              <li>https://google.com</li>
              <li>tel:0548712548</li>
            </ol>
          </div>
          <div className={styles.right}>
            <QRCodeCanvas id="canvas" value={value} size={300} includeMargin />
            <br />
            <button onClick={download}>
              <img src="download-2-64.png" alt="" />
              <span>Download</span>
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
